name: MechanicalKineticEnergy
version: '${version}'
main: org.overrun.mechanicalkineticenergy.MechanicalKineticEnergy
api-version: 1.19
authors: [ baka4n ]
description: Mechanical Kinetic Energy
website: https://github.com/XenFork/MechanicalKineticEnergy

